# Etapa de build
FROM node:20-alpine AS builder
WORKDIR /app

# Recibir las variables como argumentos de build
ARG NEXT_TELEMETRY_DISABLED
ARG NEXT_PUBLIC_AWS_REGION
ARG NEXT_PUBLIC_AWS_USER_POOL_ID
ARG NEXT_PUBLIC_AWS_USER_POOL_CLIENT_ID
ARG AWS_USER_POOL_CLIENT_SECRET
ARG NODE_ENV
ARG AWS_DISABLE_SSL_VERIFICATION

# Exportarlas como variables de entorno (para que Next.js las lea)
ENV NEXT_TELEMETRY_DISABLED=$NEXT_TELEMETRY_DISABLED
ENV NEXT_PUBLIC_AWS_REGION=$NEXT_PUBLIC_AWS_REGION
ENV NEXT_PUBLIC_AWS_USER_POOL_ID=$NEXT_PUBLIC_AWS_USER_POOL_ID
ENV NEXT_PUBLIC_AWS_USER_POOL_CLIENT_ID=$NEXT_PUBLIC_AWS_USER_POOL_CLIENT_ID
ENV AWS_USER_POOL_CLIENT_SECRET=$AWS_USER_POOL_CLIENT_SECRET
ENV NODE_ENV=$NODE_ENV
ENV AWS_DISABLE_SSL_VERIFICATION=$AWS_DISABLE_SSL_VERIFICATION

COPY package*.json ./
RUN npm ci
COPY . .

# Next.js necesita las variables en build time
RUN npm run build
