name: Build and Push to ECR

on:
  push:
    branches:
      - master  # o la rama que quieras usar

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: latest

          NEXT_TELEMETRY_DISABLED: ${{ secrets.NEXT_TELEMETRY_DISABLED }}
          NEXT_PUBLIC_AWS_REGION: ${{ secrets.NEXT_PUBLIC_AWS_REGION }}
          NEXT_PUBLIC_AWS_USER_POOL_ID: ${{ secrets.NEXT_PUBLIC_AWS_USER_POOL_ID }}
          NEXT_PUBLIC_AWS_USER_POOL_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_AWS_USER_POOL_CLIENT_ID }}
          NEXT_PUBLIC_AWS_USER_POOL_CLIENT_SECRET: ${{ secrets.NEXT_PUBLIC_AWS_USER_POOL_CLIENT_SECRET }}
          NODE_ENV: production
          AWS_DISABLE_SSL_VERIFICATION: true
        run: |
          docker build \
            --build-arg NEXT_TELEMETRY_DISABLED=$NEXT_TELEMETRY_DISABLED \
            --build-arg NEXT_PUBLIC_AWS_REGION=$NEXT_PUBLIC_AWS_REGION \
            --build-arg NEXT_PUBLIC_AWS_USER_POOL_ID=$NEXT_PUBLIC_AWS_USER_POOL_ID \
            --build-arg NEXT_PUBLIC_AWS_USER_POOL_CLIENT_ID=$NEXT_PUBLIC_AWS_USER_POOL_CLIENT_ID \
            --build-arg NEXT_PUBLIC_AWS_USER_POOL_CLIENT_SECRET=$NEXT_PUBLIC_AWS_USER_POOL_CLIENT_SECRET \
            --build-arg NODE_ENV=$NODE_ENV \
            --build-arg AWS_DISABLE_SSL_VERIFICATION=$AWS_DISABLE_SSL_VERIFICATION \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
